spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/learn_camel
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

startRoute: timer:hello?period=10s
routeFromUri: file:data/input/?delete=true&readLock=none
routeTo1Uri: file:data/output

message: DEV Environment
valueMessage: DEV value
envMessage: DEV env

---
spring:
  profiles: mock
  datasource:
    url: jdbc:postgresql://localhost:5432/learn_camel
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

startRoute: direct:input
routeFromUri: file:data/input/?delete=true&readLock=none
routeTo1Uri: mock:output

message: MOCK Environment
valueMessage: MOCK value
envMessage: MOCK env

---
spring:
  profiles: stage
  datasource:
    url: jdbc:postgresql://localhost:5432/learn_camel
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

startRoute: timer:hello?period=10s
routeFromUri: file:data/input/?delete=true&readLock=none
routeTo1Uri: file:data/output

message: STAGE Environment
valueMessage: STAGE value
envMessage: STAGE env

---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/learn_camel
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

startRoute: timer:hello?period=10s
routeFromUri: file:data/input/?delete=true&readLock=none
routeTo1Uri: file:data/output

message: PROD Environment
valueMessage: PROD value
envMessage: PROD env


