spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

startRoute: timer:hello?period=10s
routeFromUri: file:data/input/?delete=true&readLock=none
routeTo1Uri: file:data/output

message: DEV Environment
valueMessage: DEV value
envMessage: DEV env

---
spring:
  profiles: mock

startRoute: direct:input
routeFromUri: file:data/input/?delete=true&readLock=none
routeTo1Uri: mock:output

message: MOCK Environment
valueMessage: MOCK value
envMessage: MOCK env

---
spring:
  profiles: stage

startRoute: timer:hello?period=10s
routeFromUri: file:data/input/?delete=true&readLock=none
routeTo1Uri: file:data/output

message: STAGE Environment
valueMessage: STAGE value
envMessage: STAGE env

---
spring:
  profiles: prod

startRoute: timer:hello?period=10s
routeFromUri: file:data/input/?delete=true&readLock=none
routeTo1Uri: file:data/output

message: PROD Environment
valueMessage: PROD value
envMessage: PROD env


